# Generated by Django 4.2.16 on 2024-12-05 11:27

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_tag_alter_user_created_at_alter_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_id',
            field=models.IntegerField(verbose_name=users_app.models.User),
        ),
    ]
