# Generated by Django 4.2.16 on 2024-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_follower_alter_user_password_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='users_app.tag'),
        ),
    ]
