# Generated by Django 4.2.16 on 2024-12-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
